version: 0.2

phases:
  pre_build:
    commands:
    - $(aws ecr get-login --no-include-email)
    - export BUILD_TAG=$(date +"%F-%H-%M-%S")
  build:
    commands:
    - cd software
    - sh download.sh
    - cd ..
    - docker build -t my-image:latest .
  post_build:
    commands:
    # $CONTAINER_REPO is defined in the codebuild project that runs this script
    - docker tag my-image:latest $CONTAINER_REPO:$BUILD_TAG
    - docker push $CONTAINER_REPO:$BUILD_TAG
