version: 0.2

phases:
  pre_build:
    commands:
    - $(aws ecr get-login --no-include-email)
    - export BUILD_TAG=$(date +"%F-%H-%M-%S")
  build:
    commands:
    - cd software
    - sh download.sh
    - cd ..
    - docker build -t myImage .
  post_build:
    commands:
    - docker tag myImage:latest $CONTAINER_REPO:$BUILD_TAG
    - docker push $CONTAINER_REPO:$BUILD_TAG
