FROM base-stage:1.0 as mapready-stage 

RUN apt install --no-install-recommends -y \
    pkg-config \
    gcc \
    g++ \
    bison \
    flex \
    libcunit1-dev \
    libexif-dev \
    libfftw3-dev \
    libgdal-dev \
    libgeotiff-dev \
    libglade2-dev \
    libglib2.0-dev \
    libgsl-dev \
    libgtk2.0-dev \
    libjpeg-dev \
    libpng-dev \
    libproj-dev \
    libproj12 \
    libshp-dev \
    libtiff5-dev \
    libxml2-dev \
    libhdf5-dev

ENV MAPREADY_HOME /usr/local/mapready/

COPY mapready-build/bin/* $MAPREADY_HOME/bin/
COPY mapready-build/doc/* $MAPREADY_HOME/doc/
COPY mapready-build/lib/* $MAPREADY_HOME/lib/
COPY mapready-build/man/* $MAPREADY_HOME/man/
COPY mapready-build/share/* $MAPREADY_HOME/share/

ENV PATH $PATH:$MAPREADY_HOME/bin/:$MAPREADY_HOME/lib/:$MAPREADY_HOME/share/


FROM mapready-stage as mapready-stage-test 

RUN echo "Testing mapready"
