FROM base-stage: as mapready-stage 

RUN set -e 

RUN apt install -y \
    libgeo-proj4-perl \
    proj-bin \
    geotiff-bin \
    libshp-dev \
    libshp2 \
    libhdf5-dev \
    libnetcdf-dev \
    libgdal-dev

RUN ln -s /usr/lib/x86_64-linux-gnu/libgeotiff.so.5 /usr/lib/x86_64-linux-gnu/libgeotiff.so.2 && \
    ln -s /usr/lib/libgdal.so /usr/lib/libgdal.so.20


ENV MAPREADY_HOME /usr/local/mapready/

COPY mapready-build/bin/* $MAPREADY_HOME/bin/
COPY mapready-build/doc/* $MAPREADY_HOME/doc/
COPY mapready-build/lib/* $MAPREADY_HOME/lib/
COPY mapready-build/man/* $MAPREADY_HOME/man/
COPY mapready-build/share/* $MAPREADY_HOME/share/

ENV PATH $PATH:$MAPREADY_HOME/bin/:$MAPREADY_HOME/lib/:$MAPREADY_HOME/share/


FROM mapready-stage as mapready-stage-test 

RUN asf_mapready -h ; exit 0
RUN asf_geocode -h ; exit 0
