FROM base-stage: as train-stage 

RUN apt install --no-install-recommends -y \
    gdal-bin

RUN conda install  gdal==3.1.3

RUN pip install 'numpy==1.19.1' 'netCDF4==1.5.4' 'scipy==1.5.2' 'hyp3lib==1.4.1'

COPY TRAIN/ /usr/local/TRAIN/
ENV PYTHONPATH $PYTHONPATH:/usr/local/TRAIN/src

# Clean up a few other things at the end
RUN apt update && \
    rm -rf /var/lib/apt/lists/* && \
    apt autoremove -y && \
    conda clean --yes --all


FROM train-stage as train-stage-test 

COPY tests/train.sh train.sh  
RUN bash train.sh
