FROM jupyter/base-notebook:hub-1.1.0 as base-stage 

USER root

RUN apt update && \
    apt install --no-install-recommends -y \
        software-properties-common \
        git && \
    add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable && \
    apt update && \
    apt upgrade -y

# Clean up a few other things at the end
RUN conda clean --yes --all


FROM base-stage as base-stage-test

COPY tests/base.sh base.sh
RUN bash base.sh
