FROM jupyter/minimal-notebook:dc9744740e12 as base-stage 

USER root

RUN apt update && \
    apt install --no-install-recommends -y software-properties-common && \
    add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable && \
    apt update

# Remove over 1 GB of latex files to save space
RUN apt remove -y texlive*


FROM base-stage as base-stage-test
