FROM jupyter/base-notebook:lab-4.0.1 as release

# Base Stage ****************************************************************
USER root
WORKDIR /

RUN set -ve

COPY pkgs/vnc_patches/vnc.patch /tmp/vnc.patch

RUN apt update
RUN apt install --no-install-recommends -y \
        software-properties-common \
        git && \
    apt-get install -y gpg-agent && \
    add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable && \
    apt update && \
    apt upgrade -y

RUN apt install --no-install-recommends --fix-missing -y \
    ### GENERAL
    zip \
    unzip \
    wget \
    vim \
    rsync \
    less \
    snaphu \
    curl \
    openssh-client \
    libgl1-mesa-glx \
    emacs \
    gnupg2 \
    jq \
    gfortran \
    ### SNAP
    default-jdk-headless \
    ### Install texlive for PDF exporting of notebooks containing LaTex
    texlive-xetex \
    texlive-fonts-recommended \
    texlive-plain-generic \
    ### PyGMTSAR
    csh \
    autoconf \
    make \ 
    libtiff5-dev \ 
    liblapack-dev \
    libgmt-dev \
    gmt-dcw \
    gmt-gshhg \
    gmt \
    ### Jupyter Desktop
    #flatpak \
    patch \
    dbus-x11 \
    xfce4 \
    xfce4-panel \
    xfce4-session \
    xfce4-settings \
    xorg \
    xubuntu-icon-theme \
    tigervnc-standalone-server \
    tigervnc-xorg-extension

# Update conda and mamba: this breaks things in the hook, need to play with it more
# Updating just conda and mamba will auto-remove pip, so force pip to update to remain
#RUN mamba update -c conda-forge -y conda mamba pip

RUN mamba install -c conda-forge -y \
    ### Install plotting and general
    awscli \
    boto3 \
    pyyaml \
    bokeh \
    plotly \
    'pyopenssl>=23.0.0' \
    ### Install jupyter libaries
    kernda \
    # This is not compatible with JL 4: jupyter_contrib_nbextensions \ 
    jupyter-resource-usage \
    nb_conda_kernels \
    jupyterlab-spellchecker \
    ipympl \
    jupyterlab_widgets \
    ipywidgets \
    ### Dask
    dask-gateway \
    dask \
    distributed \
    ### Jupyter DEsktop
    websockify \
    --

RUN python3 -m pip install \
        ### For ASF
        url-widget \
        opensarlab-frontend==1.4.5 \
        ### For pyGMTSAR
        pygmtsar &&\
    cd / &&\
        mkdir -p /tmp/build/GMTSAR /usr/local/GMTSAR &&\
        git clone --branch master https://github.com/gmtsar/gmtsar /tmp/build/GMTSAR/ &&\
        cd /tmp/build/GMTSAR &&\
        autoconf &&\
        ./configure --with-orbits-dir=/tmp CFLAGS='-z muldefs' LDFLAGS='-z muldefs' &&\
        make &&\
        make install &&\
        mv -v /tmp/build/GMTSAR/bin /usr/local/GMTSAR/bin &&\
        rm -rf /tmp/build &&\
    cd / &&\
    ### Jupyter Desktop
    # When running a local version of this dockerfile, consult https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/47#issuecomment-1687484891
    cd / &&\
        git clone https://github.com/jupyterhub/jupyter-remote-desktop-proxy.git /opt/install &&\ 
        mv /tmp/vnc.patch /opt/install/vnc.patch &&\
        cd /opt/install &&\
        mamba env update -n base --file environment.yml &&\
        patch -p1 < vnc.patch &&\
    cd / &&\
    ### Extra stuff
    # Make sure that any files in the home directory are jovyan permission
    chown -R jovyan:users $HOME/ &&\
    # Make sure mamba (within conda) has write access
    chmod -R 777 /opt/conda/pkgs/ &&\
    # Make sure JupyterLab settings is writable
    mkdir -p /opt/conda/share/jupyter/lab/settings/ &&\
    chown jovyan:users /opt/conda/share/jupyter/lab/settings/ &&\
    chmod -R 775 /opt/conda/share/jupyter/lab/settings/ &&\
    # Add sudo group user 599 elevation
    addgroup -gid 599 elevation &&\
    echo '%elevation ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&\
    # Use the kernel display name `base` for the base conda environment
    mamba run -n base kernda --display-name base -o /opt/conda/share/jupyter/kernels/python3/kernel.json &&\
    mamba clean -y --all &&\
    mamba init &&\
    rm -rf /home/jovyan/..?* /home/jovyan/.[!.]* /home/jovyan/*

### GMTSAR
ENV PATH=/usr/local/GMTSAR/bin:$PATH

WORKDIR /home/jovyan
USER jovyan

##########################################

FROM release as testing 

COPY tests/* /tests/

RUN bash /tests/*.sh
