FROM jupyter/base-notebook:hub-1.4.2 as release

# Base Stage ****************************************************************
USER root
WORKDIR /

RUN set -ve

RUN apt update && \
    apt install --no-install-recommends -y \
        software-properties-common \
        git && \
    add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable && \
    apt update && \
    apt upgrade -y

COPY tests/* /tests/

# SNAP  ****************************************************************
RUN apt install --no-install-recommends -y \
    default-jdk-headless

# TRAIN  ****************************************************************
RUN apt install --no-install-recommends -y \
    gdal-bin

COPY TRAIN/ /usr/local/TRAIN/

RUN apt install -y \
    proj-bin \
    geotiff-bin \
    libshp-dev \
    libshp2 \
    libhdf5-dev \
    libnetcdf-dev \
    libgdal-dev \
    libgsl-dev

# Install general items. If a library is needed for a specific piece of software, put it with that software.
RUN apt update && \
    apt install --fix-missing --no-install-recommends -y \
        zip \
        unzip \
        wget \
        vim \
        rsync \
        less \
        snaphu \
        curl \
        openssh-client \
        libgl1-mesa-glx \
        emacs \
        gnupg2 \
        jq \
        gfortran

# Update conda and mamba: this breaks things in the hook, need to play with it more
RUN conda update -n base conda mamba

RUN conda install -c conda-forge awscli boto3 pyyaml bokeh mamba_gator

# Install jupyter libaries
RUN conda install -c conda-forge jupyter_contrib_nbextensions jupyter-resource-usage nb_conda_kernels jupyterlab-spellchecker ipympl kernda

#install dask libraries
RUN conda install -c conda-forge dask-gateway dask distributed -y

# Install OpenSARlab's widgets and extensions
RUN python -m pip install url-widget opensarlab-profile-label==0.1.2 opensarlab-doc-link==0.1.0 opensarlab_controlbtn==0.1.0 opensarlab-notifications==0.1.4 opensarlab-theme-light==0.1.1

# Make sure that any files in the home directory are jovyan permission
RUN chown -R jovyan:users $HOME/

# Add sudo group user 599 elevation
RUN addgroup -gid 599 elevation \
    && echo '%elevation ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# Clean up a few other things at the end
RUN apt update && \
    rm -rf /var/lib/apt/lists/* && \
    apt autoremove -y && \
    conda clean --yes --all

# Make sure mamba (within conda) has write access
RUN chmod -R 777 /opt/conda/pkgs/

# Use the kernel display name `base` for the base conda environment
RUN conda run -n base kernda --display-name base -o /opt/conda/share/jupyter/kernels/python3/kernel.json

# Set the default theme to opensarlab-theme-light to avoid issues with built-in light theme and status bar
# Remove the logout option from the main menu to steer users to the hub control panel
# Remove the launch classic notebook option to avoid broken classic terminals and image loading errors
RUN SETTINGS=/opt/conda/share/jupyter/lab/settings && \
    mkdir -p $SETTINGS && \
    OVERRIDES=$SETTINGS/overrides.json && \
    TEMP=$SETTINGS/temp && \
    echo '{"@jupyterlab/apputils-extension:themes": {"theme": "opensarlab-theme-light"}}' > $OVERRIDES && \
    jq '. += {"@jupyterlab/mainmenu-extension:plugin": {"menus": [{"id": "jp-mainmenu-file", "items": [{"command": "hub:logout", "disabled": true}]}]}}' $OVERRIDES > $TEMP && \
    jq '.["@jupyterlab/mainmenu-extension:plugin"].menus[1] |= {"id": "jp-mainmenu-help", "items": [{"command": "help:launch-classic-notebook", "disabled": true}]}' $TEMP > $OVERRIDES && \
    jq '. += {"jupyterlab-topbar-extension:plugin": {"order": ["spacer", "opensarlab_profile_label", "doc_link", "server-btn"]}}' $OVERRIDES > $TEMP && \
    mv $TEMP $OVERRIDES

RUN rm -rf /home/jovyan/..?* /home/jovyan/.[!.]* /home/jovyan/*
WORKDIR /home/jovyan
RUN conda init
USER jovyan

##########################################

FROM release as testing 

RUN bash /tests/sar.sh
