FROM jupyter/base-notebook:hub-1.4.2 as release

# Base Stage ****************************************************************
USER root
WORKDIR /

RUN set -e

RUN apt update && \
    apt install --no-install-recommends -y \
        software-properties-common \
        git && \
    add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable && \
    apt update && \
    apt upgrade -y

COPY tests/* /tests/

# SNAP  ****************************************************************
RUN apt install --no-install-recommends -y \
    default-jdk-headless

# TRAIN  ****************************************************************
RUN apt install --no-install-recommends -y \
    gdal-bin

COPY TRAIN/ /usr/local/TRAIN/

RUN apt install -y \
    proj-bin \
    geotiff-bin \
    libshp-dev \
    libshp2 \
    libhdf5-dev \
    libnetcdf-dev \
    libgdal-dev \
    libgsl-dev

# Install general items. If a library is needed for a specific piece of software, put it with that software.
RUN apt update && \
    apt install --fix-missing --no-install-recommends -y \
        zip \
        unzip \
        wget \
        vim \
        rsync \
        less \
        snaphu \
        curl \
        openssh-client \
        libgl1-mesa-glx \
        emacs \
        gnupg2 \
        jq

RUN conda install -c conda-forge awscli boto3 pyyaml bokeh

# Install jupyter libaries
RUN conda install -c conda-forge jupyter_contrib_nbextensions jupyter-resource-usage nb_conda_kernels jupyterlab-spellchecker ipympl kernda

#install dask libraries
RUN conda install -c conda-forge dask-gateway dask distributed -y

# Install OpenSARlab's widgets and extensions
RUN python -m pip install url-widget opensarlab-profile-label opensarlab-doc-link opensarlab-notifications==0.1.3 opensarlab-theme-light

# Make sure that any files in the home directory are jovyan permission
RUN chown -R jovyan:users $HOME/

# Make sure mamba (within conda) has write access
RUN chmod -R 755 /opt/conda/

# Add sudo group user 599 elevation
RUN addgroup -gid 599 elevation \
    && echo '%elevation ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# Clean up a few other things at the end
RUN apt update && \
    rm -rf /var/lib/apt/lists/* && \
    apt autoremove -y && \
    conda clean --yes --all

# Use the kernel display name `base` for the base conda environment
RUN conda run -n base kernda --display-name base -o /opt/conda/share/jupyter/kernels/python3/kernel.json

# Set the default theme to opensarlab-theme-light to avoid issues with built-in light theme and status bar
RUN SETTINGS=/opt/conda/share/jupyter/lab/settings && \
    mkdir -p $SETTINGS && \
    echo '{"@jupyterlab/apputils-extension:themes": {"theme": "opensarlab-theme-light"}}' > $SETTINGS/overrides.json

RUN rm -rf /home/jovyan/..?* /home/jovyan/.[!.]* /home/jovyan/*
WORKDIR /home/jovyan
RUN conda init
USER jovyan

##########################################

FROM release as testing 

RUN bash /tests/sar.sh
