FROM base-stage: as isce-stage

ENV ISCE_HOME /opt/isce2/isce/
ENV PYTHONPATH $PYTHONPATH:/opt/isce2
ENV PATH $PATH:$ISCE_HOME/bin:$ISCE_HOME/applications

RUN apt install --no-install-recommends -y \
    libfftw3-dev \
    libxm4

RUN conda install gdal==3.0.2 libgcc

RUN pip install 'numpy' 'h5py' 'scipy'

COPY --from=isce-native: /opt/isce2/isce $ISCE_HOME

# Add extra files to ISCE
COPY topo.py $ISCE_HOME/applications/
COPY unpackFrame_ALOS_raw.py $ISCE_HOME/applications/
RUN chmod 755 $ISCE_HOME/applications/*

# So that users can temporarily add items to ISCE
RUN chown -R jovyan:root $ISCE_HOME

# Clean up a few other things at the end
RUN apt update && \
    rm -rf /var/lib/apt/lists/* && \
    apt autoremove -y && \
    conda clean --yes --all


FROM isce-stage as isce-stage-test

RUN echo "Testing isce"

# A few tests for largely possible debugging, make errors as warnings 
RUN python3.8 $ISCE_HOME/applications/topsApp.py --help ; exit 0
RUN python3.8 -c "import isce; print(isce.__version__)" ; exit 0
RUN python3.8 -c "from isce.applications import topsApp" ; exit 0

RUN gdalinfo --help ; exit 0
