FROM base-stage: as isce-stage

ENV ISCE_HOME /opt/isce2/isce/
ENV PYTHONPATH $PYTHONPATH:/opt/isce2
ENV PATH $PATH:$ISCE_HOME/bin:$ISCE_HOME/applications

RUN apt install --no-install-recommends -y \
    libfftw3-dev \
    libxm4

RUN conda create -y -n isce python=3.8 && \
    conda install -n isce \
        gdal libgcc numpy h5py scipy
RUN conda init bash

RUN cp /opt/conda/envs/isce/lib/libgdal.so.27 /opt/conda/envs/isce/lib/libgdal.so.26

COPY --from=isce-native: /opt/isce2/isce $ISCE_HOME

# Add extra files to ISCE
COPY topo.py $ISCE_HOME/applications/
COPY unpackFrame_ALOS_raw.py $ISCE_HOME/applications/
RUN chmod 755 $ISCE_HOME/applications/*

# So that users can temporarily add items to ISCE
RUN chown -R jovyan:root $ISCE_HOME

# Clean up a few other things at the end
RUN apt update && \
    rm -rf /var/lib/apt/lists/* && \
    apt autoremove -y && \
    conda clean --yes --all


FROM isce-stage as isce-stage-test

COPY tests/isce.sh isce.sh
RUN bash isce.sh
