FROM base-stage:1.0 as general_cpu

# Start
COPY --from=start-stage:1.0 / /

# Isce
ENV ISCE_HOME /opt/isce2/isce/
ENV PYTHONPATH $PYTHONPATH:/opt/isce2
ENV PATH $PATH:$ISCE_HOME/bin:$ISCE_HOME/applications
COPY --from=isce-stage:1.0 / / 

# Mapready
ENV MAPREADY_HOME /usr/local/mapready/
ENV PATH $PATH:$MAPREADY_HOME/bin/:$MAPREADY_HOME/lib/:$MAPREADY_HOME/share/
COPY --from=mapready-stage:1.0 / /

# Snap
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
ENV PATH $PATH:/usr/lib/jvm/java-11-openjdk-amd64/bin
COPY --from=snap-stage:1.0 / /

# ARIA
ENV ARIA_TOOLS_HOME=/usr/local/ARIA-tools
ENV ARIA_TOOLS_DOCS_HOME=/usr/local/ARIA-tools-docs
COPY --from=aria-stage:1.0 / /

# MintPy
ENV MINTPY_HOME=/usr/local/MintPy
ENV PYAPS_HOME=/usr/local/PyAPS
ENV PATH=${PATH}:${MINTPY_HOME}/mintpy:${MINTPY_HOME}/sh
ENV PYTHONPATH=${PYTHONPATH}:${MINTPY_HOME}:${PYAPS_HOME}
ENV PROJ_LIB=/usr/share/proj
COPY --from=mintpy-stage:1.0 / /

# Train
ENV PYTHONPATH $PYTHONPATH:/usr/local/TRAIN/src
COPY --from=train-stage:1.0 / /

# Giant 
ENV PYTHONPATH $PYTHONPATH:/usr/local/GIAnT:/usr/local/GIAnT/SCR:/usr/local/GIAnT/tsinsar:/usr/local/GIAnT/examples:/usr/local/GIAnT/geocode:/usr/local/GIAnT/solver
COPY --from=giant-stage:1.0 / /

# Finale
COPY --from=finale-stage:1.0 / /

USER jovyan

##########################################

FROM general_cpu as general_cpu-test 

RUN set -e

# Python
RUN python --version 
RUN python3.7 --version 
RUN python2 --version
RUN python2.7 --version

# ISCE
RUN python3.7 $ISCE_HOME/applications/topsApp.py --help ; exit 0
RUN python3.7 -c "import isce; print(isce.__version__)" ; exit 0
RUN python3.7 -c "from isce.applications import topsApp" ; exit 0

# gdal
RUN gdalwarp --help ; exit 0

# mapready
RUN asf_mapready --help ; exit 0
RUN asf_geocode --help ; exit 0

# MintPy
RUN python3.7 -c "import numpy" ; exit 0
RUN python3.7 -c "from mintpy import view, tsview, plot_network, plot_transection, plot_coherence_matrix" ; exit 0

# ARIA
RUN ariaDownload.py --help ; exit 0
RUN smallbaselineApp.py --help ; exit 0

# Train
RUN python3.7 /usr/local/TRAIN/src/aps_weather_model.py -h ; exit 0

# giant
RUN python2.7 /usr/local/GIAnT/SCR/ProcessStack.py -h ; exit 0

# snap
RUN /usr/local/snap/bin/gpt -h ; exit 0
