FROM base-stage: as build

COPY --from=isce-stage: / / 
COPY --from=snap-stage: / /
COPY --from=aria-stage: / /
COPY --from=train-stage: / /
COPY --from=mintpy-stage: / /
COPY --from=mapready-stage: / /
COPY --from=finale-stage: / /

##########################################

FROM base-stage: as release

COPY --from=build / /

# Enviroments don't get copied over on COPY
ENV ISCE_HOME /opt/isce2/isce/
ENV PYTHONPATH $PYTHONPATH:/opt/isce2
ENV PATH $PATH:$ISCE_HOME/bin:$ISCE_HOME/applications

ENV MAPREADY_HOME /usr/local/mapready/
ENV PATH $PATH:$MAPREADY_HOME/bin/:$MAPREADY_HOME/lib/:$MAPREADY_HOME/share/

ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
ENV PATH $PATH:/usr/lib/jvm/java-11-openjdk-amd64/bin

ENV ARIA_TOOLS_HOME=/usr/local/ARIA-tools
ENV ARIA_TOOLS_DOCS_HOME=/usr/local/ARIA-tools-docs

ENV PYTHONPATH $PYTHONPATH:/usr/local/TRAIN/src

ENV MINTPY_HOME=/usr/local/MintPy
ENV PYAPS_HOME=/usr/local/PyAPS
ENV PATH=${PATH}:${MINTPY_HOME}/mintpy:${MINTPY_HOME}/sh
ENV PYTHONPATH=${PYTHONPATH}:${MINTPY_HOME}:${PYAPS_HOME}
ENV PROJ_LIB=/usr/share/proj

USER jovyan

##########################################

FROM release as testing 

COPY tests.sh tests.sh 
RUN bash tests.sh
