FROM base-stage:1.0 as mintpy-stage

ENV MINTPY_HOME=/usr/local/MintPy
ENV PYAPS_HOME=/usr/local/PyAPS
ENV PATH=${PATH}:${MINTPY_HOME}/mintpy:${MINTPY_HOME}/sh
ENV PYTHONPATH=${PYTHONPATH}:${MINTPY_HOME}:${PYAPS_HOME}
ENV PROJ_LIB=/usr/share/proj

# Pull and config mintpy and pyaps
COPY MintPy ${MINTPY_HOME}
COPY PyAPS ${PYAPS_HOME}/pyaps3

RUN apt install --no-install-recommends -y \
        cython3 \
        proj-bin \
        libgeos-3.6.2 \
        libgeos-dev \
        libproj-dev
RUN pip install 'cdsapi' 'cvxopt' 'dask[complete]>=1.0,<2.0' 'dask-jobqueue>=0.3,<1.0' cython \
    'h5py' 'lxml' 'matplotlib==3.1.3' 'netcdf4' 'numpy' 'pyproj' 'pykdtree' 'pyresample' 'scikit-image' 'scipy'
RUN pip install git+https://github.com/SciTools/cartopy.git --no-binary cartopy  # dev version
RUN pip install pykml -e git+https://github.com/yunjunz/pykml.git#egg=pykml


FROM mintpy-stage as mintpy-stage-test 

RUN echo "Testing mintpy"
