FROM base-stage: as mintpy-stage

ENV MINTPY_HOME=/usr/local/MintPy
ENV PYAPS_HOME=/usr/local/PyAPS
ENV PATH=${PATH}:${MINTPY_HOME}/mintpy:${MINTPY_HOME}/sh
ENV PYTHONPATH=${PYTHONPATH}:${MINTPY_HOME}:${PYAPS_HOME}
ENV PROJ_LIB=/usr/share/proj

# Pull and config mintpy and pyaps
COPY MintPy ${MINTPY_HOME}
COPY PyAPS ${PYAPS_HOME}/pyaps3

# numpy >= 1.19.1, scipy >= 1.5.2, gdal >= 3.1.3 
RUN conda install  -y --file $MINTPY_HOME/docs/conda.txt
RUN pip install pykml -e git+https://github.com/yunjunz/pykml.git#egg=pykml

# Clean up a few other things at the end
RUN apt update && \
    rm -rf /var/lib/apt/lists/* && \
    apt autoremove -y && \
    conda clean --yes --all


FROM mintpy-stage as mintpy-stage-test 

COPY tests/mintpy.sh mintpy.sh
RUN bash mintpy.sh
