FROM base-stage: as mintpy-stage

ENV MINTPY_HOME=/usr/local/MintPy
ENV PYAPS_HOME=/usr/local/PyAPS
ENV PATH=${PATH}:${MINTPY_HOME}/mintpy:${MINTPY_HOME}/sh
ENV PYTHONPATH=${PYTHONPATH}:${MINTPY_HOME}:${PYAPS_HOME}
ENV PROJ_LIB=/usr/share/proj

# Pull and config mintpy and pyaps
COPY MintPy ${MINTPY_HOME}
COPY PyAPS ${PYAPS_HOME}/pyaps3

RUN conda install -y --file $MINTPY_HOME/docs/conda.txt
RUN pip install pykml -e git+https://github.com/yunjunz/pykml.git#egg=pykml

# Clean up a few other things at the end
RUN apt update && \
    rm -rf /var/lib/apt/lists/* && \
    apt autoremove -y && \
    conda clean --yes --all


FROM mintpy-stage as mintpy-stage-test 

RUN python3.8 -c "import numpy"
RUN python3.8 -c "from mintpy import view, tsview, plot_network, plot_transection, plot_coherence_matrix"
RUN smallbaselineApp.py -h
