FROM base-stage: as finale-stage

# Manually update nbconvert. A dicrepancy in the versioning causes a 500 when opening a notebook. https://github.com/jupyter/notebook/issues/3629#issuecomment-399408222
# Remember, here pip is updating within the condas namespace where jupyter notebook items are held.
RUN pip install --upgrade nbconvert

# Downgrade tornado otherwise the notebook can't connect to the notebook server. https://github.com/jupyter/notebook/issues/2664#issuecomment-468954423
RUN pip install tornado==5.1.1  # 4.5.3

# Install general items. If a library is needed for a specific piece of software, put it with that software.
RUN apt install --no-install-recommends -y \
    zip \
    unzip \
    wget \
    vim \
    rsync \
    less \
    snaphu \
    curl

RUN pip install 'awscli' 'boto3>=1.4.4' 'pyyaml>=3.12' 'matplotlib==3.3.2' 'bokeh'

# Install any other custom and jupyter libaries like widgets
# Use pip (conda version) since we want to corner off GIAnT's work and also run it with Jupyter
RUN pip install asf-hyp3
RUN conda install -c conda-forge jupyter_contrib_nbextensions -y

# Remove 'LaTeX' options and all custom exporters in download menu
RUN sed -i '/LaTeX/d' /opt/conda/lib/python3.8/site-packages/notebook/templates/notebook.html && \
    sed -i '/exporter\.display/d' /opt/conda/lib/python3.8/site-packages/notebook/templates/notebook.html

# Make sure that any files in the home directory are jovyan permission
RUN chown -R jovyan:users $HOME/

# Add sudo group user 599 elevation
RUN addgroup -gid 599 elevation \
    && echo '%elevation ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# Add jupyter hooks
COPY jupyter-hooks /etc/jupyter-hooks
RUN chmod -R 755 /etc/jupyter-hooks && \
    chown -R jovyan:users /etc/jupyter-hooks

# So that users can temporarily install conda packages and avoid a special environment
RUN chown -R jovyan:root /opt/conda

# Clean up a few other things at the end
RUN apt update && \
    rm -rf /var/lib/apt/lists/* && \
    apt autoremove -y && \
    conda clean --yes --all

RUN mkdir -p /envs && touch /envs/finale-stage.env && env > /envs/finale-stage.env


FROM finale-stage as finale-stage-test 

COPY tests/finale.sh finale.sh
RUN bash finale.sh
