FROM base-stage: as aria-stage

ENV ARIA_TOOLS_HOME=/usr/local/ARIA-tools
ENV ARIA_TOOLS_DOCS_HOME=/usr/local/ARIA-tools-docs

# Tools
COPY ARIA-tools ${ARIA_TOOLS_HOME}
RUN pip install 'shapely' 'joblib' && \
    cd ${ARIA_TOOLS_HOME} && \
    python setup.py install && \
    cd /

# Docs
COPY ARIA-tools-docs ${ARIA_TOOLS_DOCS_HOME}

# Clean up a few other things at the end
RUN apt update && \
    rm -rf /var/lib/apt/lists/* && \
    apt autoremove -y && \
    conda clean --yes --all


FROM aria-stage as aria-stage-test 

RUN echo "Testing aria"
